# Generated by Django 3.2.10 on 2022-01-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0004_vendeur'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='oui_condition',
            field=models.BooleanField(default=False),
        ),
    ]
