# Generated by Django 3.2.10 on 2022-01-31 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0006_auto_20220131_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='deleted_at',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
