# Generated by Django 3.2.10 on 2022-01-31 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0007_alter_categorie_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='updated_at',
            field=models.DateTimeField(default='', null=True),
        ),
    ]
