# Generated by Django 3.2.10 on 2022-01-31 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0008_alter_categorie_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='deleted_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='firstsouscategorie',
            name='deleted_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='firstsouscategorie',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='helperword',
            name='deleted_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='helperword',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='imageproduit',
            name='deleted_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imageproduit',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='deleted_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produit',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='secondsouscategorie',
            name='deleted_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='secondsouscategorie',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='deleted_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vendeur',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
