# Generated by Django 3.2.10 on 2022-02-01 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0010_ipmembre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ipAdress',
        ),
        migrations.AddField(
            model_name='ipmembre',
            name='continent',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ipmembre',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ipmembre',
            name='timeZone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='registerCookie',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ipmembre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ipmembre',
            name='ip',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ipmembre',
            name='nationalite',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='is_verified',
            field=models.CharField(default='non', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(null=True)),
                ('tempsSender', models.DateTimeField()),
                ('tempsReceiver', models.DateTimeField()),
                ('tempsServer', models.DateTimeField(auto_now_add=True)),
                ('estIlImage', models.ImageField(blank=True, null=True, upload_to='')),
                ('expediteur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
