# Generated by Django 3.2.10 on 2022-02-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0012_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('location', 'location'), ('donation', 'donation'), ('vente', 'vente'), ('echange', 'echange')], default='vente', max_length=255),
        ),
        migrations.AddField(
            model_name='produit',
            name='prix',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='produit',
            name='quantite',
            field=models.IntegerField(null=True),
        ),
    ]
