# Generated by Django 3.2.10 on 2022-02-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0013_auto_20220201_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='location',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('echange', 'echange'), ('vente', 'vente'), ('location', 'location'), ('donation', 'donation')], default='vente', max_length=255),
        ),
    ]
