# Generated by Django 3.2.10 on 2022-02-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0014_auto_20220201_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helperword',
            name='produit',
        ),
        migrations.AddField(
            model_name='helperword',
            name='produit',
            field=models.ManyToManyField(to='marwacoin.Produit'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('donation', 'donation'), ('vente', 'vente'), ('location', 'location'), ('echange', 'echange')], default='vente', max_length=255),
        ),
    ]
