# Generated by Django 3.2.10 on 2022-02-01 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0015_auto_20220201_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='firstSousCat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marwacoin.firstsouscategorie'),
        ),
        migrations.AddField(
            model_name='produit',
            name='secondSousCat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marwacoin.secondsouscategorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('donation', 'donation'), ('vente', 'vente'), ('echange', 'echange'), ('location', 'location')], default='vente', max_length=255),
        ),
    ]
