# Generated by Django 3.2.10 on 2022-02-01 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0018_auto_20220201_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='affiche',
            field=models.ImageField(blank=True, default='OIP.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='produit',
            name='vebdu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cause',
            field=models.CharField(choices=[('la deuxiem echoix', 'la deuxiem choices'), ('demande une partenaire', 'demande une partenaire')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('location', 'location'), ('donation', 'donation'), ('echange', 'echange'), ('vente', 'vente')], default='vente', max_length=255),
        ),
    ]
