# Generated by Django 3.2.10 on 2022-02-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0019_auto_20220201_1754'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='vebdu',
            new_name='vendu',
        ),
        migrations.AlterField(
            model_name='contact',
            name='cause',
            field=models.CharField(choices=[('demande une partenaire', 'demande une partenaire'), ('la deuxiem echoix', 'la deuxiem choices')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('location', 'location'), ('donation', 'donation'), ('vente', 'vente'), ('echange', 'echange')], default='vente', max_length=255),
        ),
    ]
