# Generated by Django 3.2.10 on 2022-02-01 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0020_auto_20220201_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='slug',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cause',
            field=models.CharField(choices=[('la deuxiem echoix', 'la deuxiem choices'), ('demande une partenaire', 'demande une partenaire')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='expediteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marwacoin.profile'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('donation', 'donation'), ('vente', 'vente'), ('location', 'location'), ('echange', 'echange')], default='vente', max_length=255),
        ),
    ]
