# Generated by Django 3.2.10 on 2022-02-01 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0025_auto_20220201_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='tache',
            field=models.CharField(choices=[('destination', 'destination'), ('reception', 'reception')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('vente', 'vente'), ('location', 'location'), ('echange', 'echange'), ('donation', 'donation')], default='vente', max_length=255),
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marwacoin.produit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
