# Generated by Django 3.2.10 on 2022-02-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0026_auto_20220201_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorie',
            name='slug',
            field=models.CharField(default='AZERTY', max_length=255),
        ),
        migrations.AddField(
            model_name='firstsouscategorie',
            name='slug',
            field=models.CharField(default='AZERTY', max_length=255),
        ),
        migrations.AddField(
            model_name='secondsouscategorie',
            name='slug',
            field=models.CharField(default='AZERTY', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cause',
            field=models.CharField(choices=[('la deuxiem echoix', 'la deuxiem choices'), ('demande une partenaire', 'demande une partenaire')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('location', 'location'), ('donation', 'donation'), ('vente', 'vente'), ('echange', 'echange')], default='vente', max_length=255),
        ),
    ]
