# Generated by Django 3.2.10 on 2022-02-03 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0028_auto_20220203_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendeur',
            name='description',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='tache',
            field=models.CharField(choices=[('reception', 'reception'), ('destination', 'destination')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('donation', 'donation'), ('vente', 'vente'), ('echange', 'echange'), ('location', 'location')], default='vente', max_length=255),
        ),
    ]
