# Generated by Django 3.2.10 on 2022-02-05 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0030_alter_produit_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cause',
            field=models.CharField(choices=[('la deuxiem echoix', 'la deuxiem choices'), ('demande une partenaire', 'demande une partenaire')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('echange', 'echange'), ('vente', 'vente'), ('donation', 'donation'), ('location', 'location')], default='vente', max_length=255),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='marwacoin.produit')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
