# Generated by Django 3.2.10 on 2022-02-05 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0031_auto_20220205_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('created_at',), 'verbose_name': 'order', 'verbose_name_plural': 'orders'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='deleted_at',
            new_name='paid',
        ),
        migrations.RemoveField(
            model_name='order',
            name='produit',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='adress',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cause',
            field=models.CharField(choices=[('demande une partenaire', 'demande une partenaire'), ('la deuxiem echoix', 'la deuxiem choices')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='tache',
            field=models.CharField(choices=[('destination', 'destination'), ('reception', 'reception')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('location', 'location'), ('vente', 'vente'), ('echange', 'echange'), ('donation', 'donation')], default='vente', max_length=255),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='marwacoin.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='marwacoin.produit')),
            ],
            options={
                'verbose_name': 'OrderItem',
                'verbose_name_plural': 'OrdersItem',
            },
        ),
    ]
