# Generated by Django 3.2.10 on 2022-02-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0033_auto_20220205_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='nbPiece',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cause',
            field=models.CharField(choices=[('demande une partenaire', 'demande une partenaire'), ('la deuxiem echoix', 'la deuxiem choices')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='tache',
            field=models.CharField(choices=[('destination', 'destination'), ('reception', 'reception')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('vente', 'vente'), ('location', 'location'), ('donation', 'donation'), ('echange', 'echange')], default='vente', max_length=255),
        ),
    ]
