# Generated by Django 3.2.10 on 2022-02-05 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0034_auto_20220205_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='livre',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cause',
            field=models.CharField(choices=[('la deuxiem echoix', 'la deuxiem choices'), ('demande une partenaire', 'demande une partenaire')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('echange', 'echange'), ('donation', 'donation'), ('vente', 'vente'), ('location', 'location')], default='vente', max_length=255),
        ),
    ]
