# Generated by Django 3.2.10 on 2022-02-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0035_auto_20220205_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendeur',
            name='Paypal_business',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='tache',
            field=models.CharField(choices=[('reception', 'reception'), ('destination', 'destination')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('donation', 'donation'), ('echange', 'echange'), ('location', 'location'), ('vente', 'vente')], default='vente', max_length=255),
        ),
    ]
