# Generated by Django 3.2.10 on 2022-02-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0036_auto_20220206_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cause',
            field=models.CharField(choices=[('Signaler un probléme', 'Signaler un probléme'), ('Un contract de partenariat', 'Un contract de partenariat'), ('Suggérer une fonctionnalité', 'Suggérer une fonctionnalité')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('donation', 'donation'), ('échange', 'échange'), ('louer', 'louer'), ('vente', 'vente')], default='vente', max_length=255),
        ),
        migrations.DeleteModel(
            name='Conversation',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
