# Generated by Django 3.2.10 on 2022-02-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0038_auto_20220209_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='destination',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='vendeur',
            name='prixDelivration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cause',
            field=models.CharField(choices=[('Suggérer une fonctionnalité', 'Suggérer une fonctionnalité'), ('Un contract de partenariat', 'Un contract de partenariat'), ('Signaler un probléme', 'Signaler un probléme')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('louer', 'louer'), ('donation', 'donation'), ('échange', 'échange'), ('vente', 'vente')], default='vente', max_length=255),
        ),
    ]
