# Generated by Django 3.2.10 on 2022-03-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0039_auto_20220210_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='etat',
            field=models.CharField(choices=[('presq neuf', 'presq neuf'), ('bon état', 'bon état'), ('neuf', 'neuf'), ('occasion', 'occasion')], default='normal', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cause',
            field=models.CharField(choices=[('Signaler un probléme', 'Signaler un probléme'), ('Un contract de partenariat', 'Un contract de partenariat'), ('Suggérer une fonctionnalité', 'Suggérer une fonctionnalité')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('donation', 'donation'), ('louer', 'louer'), ('échange', 'échange'), ('vente', 'vente')], default='vente', max_length=255),
        ),
    ]
