# Generated by Django 3.2.10 on 2022-03-30 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0040_auto_20220330_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produit',
            name='contenu',
            field=models.TextField(default="aucun desrioption de produit veiller contacter le responsable du produit pour plusieur d'inforamation"),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('échange', 'échange'), ('donation', 'donation'), ('vente', 'vente'), ('louer', 'louer')], default='vente', max_length=255),
        ),
    ]
