# Generated by Django 3.2.10 on 2022-03-30 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0042_auto_20220330_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firstsouscategorie',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='marwacoin.categorie'),
        ),
        migrations.AlterField(
            model_name='produit',
            name='etat',
            field=models.CharField(choices=[('bon état', 'bon état'), ('presq neuf', 'presq neuf'), ('neuf', 'neuf'), ('occasion', 'occasion')], default='normal', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('louer', 'louer'), ('vente', 'vente'), ('échange', 'échange'), ('donation', 'donation')], default='vente', max_length=255),
        ),
        migrations.AlterField(
            model_name='secondsouscategorie',
            name='firstCategore',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firstCategorie', to='marwacoin.firstsouscategorie'),
        ),
    ]
