# Generated by Django 3.2.10 on 2022-03-30 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marwacoin', '0043_auto_20220330_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cause',
            field=models.CharField(choices=[('Un contract de partenariat', 'Un contract de partenariat'), ('Signaler un probléme', 'Signaler un probléme'), ('Suggérer une fonctionnalité', 'Suggérer une fonctionnalité')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='contenu',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='etat',
            field=models.CharField(choices=[('neuf', 'neuf'), ('occasion', 'occasion'), ('bon état', 'bon état'), ('presq neuf', 'presq neuf')], default='normal', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='operation',
            field=models.CharField(choices=[('échange', 'échange'), ('donation', 'donation'), ('vente', 'vente'), ('louer', 'louer')], default='vente', max_length=255),
        ),
    ]
