from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.auth import views as authViews

urlpatterns=[
	path("index", views.principal, name="principal"),
    path("", views.indexFunction, name='index'),
    path('user/parametre', views.userAccountParametre, name="parametres"),
    path('user/parametre/desactiverCompte', views.supprimerUser, name="estIlSure"),
    path('user/parametre/changeMode', views.supprimerMode, name="supprimerModeVendeur"),
	path("register/", views.register, name="register"),
    path("login/", views.user_login, name="login"),
    path("logout", views.user_logout, name="logout"),
    path('verification_de_compte/', views.verification_de_compte, name="verification_de_compte"),
    path("visiteur/home/", views.landing_page, name="home_page"),
    path("visiteur/annonceur/", views.passeModeAnnonceur, name="passeMode"),
    path("annonceur/publication/", views.publierAnnonce, name="publierAnnonce"),
    path("annonceur/publication/image/", views.publierAnnonceImage, name="publierAnnonceImage"),
    path("annonce/obtenirSousCat/<str:pk>", views.obtenirSousCategorie, name="obteniSousCat"),
    path("annonce/obtenirSecondSousCat/<str:pk>", views.obtenirSecondSousCategorie, name="obteniSecondSousCat"),
    path("user/profile/", views.profile, name="profile"),
    path('user/profile/update/', views.profile_update, name="updateprofile"),
    path('annonce/update/<str:pk>', views.updateProduct, name="updateProduct"),
    path('annonce/delete/<str:pk>', views.deleteProduct, name="deleteProduct"),
    path('visiteur/categorie/<str:slugCatPrincipal>', views.categoriesDetail, name="categoriesDetail"),
    path('visiteur/scategorie/<str:slugCatPrincipal>/<str:slugCatSecondaire>', views.firstSouscategoriesDetail, name="firstSouscategoriesDetail"),
    path('visiteur/ssdetail/<str:slugCatPrincipal>/<str:slugCatSecondaire>/<str:slugCatThird>', views.secondSousCategoriesDetail, name='secondSousCategoriesDetail'),
    path('annonceur/profile/annonces', views.afficherMesAnnonces, name='afficherMesAnnonces'),
    path('annonceur/annonces/detail', views.afficherMesAnnoncesDetail, name='afficherMesAnnoncesDetail'),
    path('produit/affiche/<str:pk>', views.versAcheterUnProduit, name='versAcheterUnProduit'),
    path('produit/rendezVous/<str:slug>', views.prendreUnRendezVous, name='prendreUnRendezVous'),
    path('produit/annonceur/contacter/<str:slug>', views.contacterVendeur, name='contacterVendeur'),
    path('produit/enregistrer/<str:pk>', views.enregistrerProduit, name='enregistrerProduit'),
    path('produit/configAchat/<str:slug>', views.configAchat, name="configAchat"),
    path('produit/payementPaypal/<str:pk>', views.payementPaypal, name='payementPaypal'),
    path('produits/paye', views.coursPayement, name="produitspaye"),
    path('root/add/categorie', views.addCatgeorie, name='addCategorie'),
    path('root/add/souscategorie', views.addFirstSousCat, name="addScategorie"),
    path('root/add/secondsouscategorie', views.addSecondSousCat, name="addSScategorie"),
    path('visiteur/notification/<str:pk>', views.lireNotification, name='lireNotification'),
    path('visiteur/enregistrement', views.voirMesEnreg, name='voirMesEnreg'),
    path('visiteur/product/delete/<str:slug>', views.deleteProductFromEnreg, name='deleteProductFromEnreg'),
    path('visiteur/Commandes', views.voirMesCommandes, name='voirMesCommandes'),
    path('visiteur/commandes/comfirmer/<str:pk>', views.confirmerDelivration, name='confirmerDelivration'),
    path('annonceur/commandes/vendu', views.mesProduitsVendu, name='mesProduitsVendu'),
    path('root/marwa/home', views.adminHome, name="admin_home"),
    path('root/show/users', views.showSiteUsers, name='showUsers'),
    path('root/show/user/<str:slug>',views.detailUser, name='detailUser'),
    path('root/produits/supprimer/<str:slug>', views.adminSupprimerProduits, name='adminSupprimerProduits'),
    path('root/vendeur/supprimer/<str:pk>', views.supprimerVendeur, name='supprimerVendeur'),
    path('vendeur/commandes/nonlivre', views.commandeNonLivre, name='commandesNonLivre'),
    path('vendeur/nonlivre/detail/<str:pk>', views.nonDelivreDetail, name='nonDelivreDetail'),
    path('root/show/user/email/<str:pk>', views.adminEnvoieEmailPourUtilisateur, name='adminEnvoieEmailPourUtilisateur'),
    path('root/messages', views.voirContactMessages, name='voirMessages'),
    path("annonce/modele/<int:pk>/<int:idprod>", views.createContenuAnnonceAvecModele, name="choisirUnModele"),
    path("annonce/categorie", views.choisirCatPourAnnonce, name="choisirCatPourAnnonce"),
    path("annonce/firstCat/<int:pk>", views.choisitFirstCatPourAnnonce, name="choisitFirstCatPourAnnonce"),
    path("annonce/secondCat/<int:pk>", views.choisirSecondCatPourAnnonce, name="choisirSecondCatPourAnnonce"),
    path("annonce/autre_information/<int:pk>", views.creerAutreInfoPourAnnonce, name="creerAutreInfoPourAnnonce"),
    #paypal urls
   
    #path('paypal/visiteur/payement/home', views.homePaypal, name="homePaypal"),
    path('visiteur/paypal-return', views.paypal_return, name="paypal-return"),
    path('visiteur/paypal-cancel', views.paypal_cancel, name="paypal-cancel"),
    #urls vers les pages statiques du site
    path('site/statique/aprpos/', views.apropos, name="apropos"),
    path('site/statique/contact/', views.visiteurContact, name="visiteurContact"),
    path('site/statique/politique/', views.politiqueDeConfidentialite, name="politiqueDeConfidentialite"),
    #des choses standard pour reset password 
    path('reset_password/', authViews.PasswordResetView.as_view(template_name= "visiteur/password_reset.html"), name="reset_password"),
    path('reset_password_sent/', authViews.PasswordResetDoneView.as_view(template_name= "visiteur/password_reset_sent.html"), name="password_reset_done"),
    path('reset/<uidb64>/<token>/', authViews.PasswordResetConfirmView.as_view(template_name= "visiteur/password_reset_form.html"), name="password_reset_confirm"),
    path('reset_password_complete/', authViews.PasswordResetCompleteView.as_view(template_name= "visiteur/password_reset_done.html"), name="password_reset_complete"),
]